name: Auto Commit and Push

on:
  schedule:
    # Gündə 4 dəfə işləyir
    - cron: "0 0,6,12,18 * * *"
  workflow_dispatch: # Manual işə salmaq üçün

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Repository-ni yoxlamaq
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Git istifadəçisini konfiqurasiya etmək
      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Step 3: Skripti icraedilən etmək (əgər varsa)
      - name: Make Script Executable
        run: |
          if [ -f "./update_script.sh" ]; then
            chmod +x ./update_script.sh
          else
            echo "update_script.sh not found, skipping."
          fi

      # Step 4: Skripti icra etmək
      - name: Run Update Script
        run: |
          if [ -f "./update_script.sh" ]; then
            ./update_script.sh
          else
            echo "update_script.sh not found, skipping."
          fi

      # Step 5: Dəyişiklikləri Git-ə əlavə etmək
      - name: Add Changes
        run: git add -A

      # Step 6: Random commit mesajı ilə commit etmək
      - name: Commit Changes
        run: |
          MESSAGES=("Update content" "Minor adjustments" "Improved automation" "Synced latest changes" "Refactor updates" "Fixed minor issues")
          RANDOM_MESSAGE=${MESSAGES[$RANDOM % ${#MESSAGES[@]}]}
          git commit -m "${RANDOM_MESSAGE}" || echo "No changes to commit"

      # Step 7: Dəyişiklikləri push etmək
      - name: Push Changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/s3bu7i/365.git
          git push origin main || echo "Push failed. Check token permissions or branch protection rules."
