name: Daily Commit

on:
  schedule:
    - cron: "0 5 * * *"  # Hər gün saat 05:00 UTC (sənin vaxtınla ~09:00)

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make a dummy change
        run: |
          echo "$(date)" >> activity.log

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add activity.log
          git commit -m "Daily contribution: $(date)" || echo "Nothing to commit"
          git push
