name: Update Script Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-script-job:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository-ni klonlayır
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Git konfiqurasiyasını təyin edir
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 3. İş qovluğunu yoxlayır
      - name: Check working directory
        run: pwd

      # 4. Faylları siyahıya salır
      - name: List all files
        run: ls -al

      # 5. Skripti icra etməzdən əvvəl onu icazəli edir
      - name: Make script executable
        run: chmod +x ./update_script.sh

      # 6. Skripti icra edir
      - name: Run update script
        run: ./update_script.sh
